# -*- coding: utf-8 -*-
"""XGBoost_based_system_for_financial_fraud_detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MbgsXoY7K89rPBaGnZwf6-Kc-lu6WTp_

Link to the paper: https://www.e3s-conferences.org/articles/e3sconf/pdf/2020/74/e3sconf_ebldm2020_02042.pdf
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
from xgboost import XGBClassifier

!pwd

dataset = pd.read_csv('drive/MyDrive/Colab Notebooks/creditcard.csv')

dataset.head()

dataset.drop(['Time'], axis=1, inplace=True)

X = dataset.drop(['Class'], axis=1).values
y = dataset['Class'].values

X.shape, y.shape

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.9)

xgb = XGBClassifier(n_estimators=5000, learning_rate=0.01, subsample=0.8, max_depth=15, colsample_bytree=0.8, tree_method='gpu_hist')

xgb.fit(X_train, y_train)

y_predicted = xgb.predict(X_test)

print(classification_report(y_predicted, y_test))

print(accuracy_score(y_predicted, y_test))

tn, fp, fn, tp = confusion_matrix(y_test, y_predicted).ravel()
print(tn, fp)
print(fn, tp)

